package com.elimu.io.nccn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Disease implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Disease() {
    }




}