package com.elimu.io.nccn;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Treatment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("step")
	private java.lang.String step;
	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label(value = "treatmentStartDate")
	private java.util.Date treatmentStartDate;

	public Treatment() {
	}

	public java.lang.String getStep() {
		return this.step;
	}

	public void setStep(java.lang.String step) {
		this.step = step;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.util.Date getTreatmentStartDate() {
		return this.treatmentStartDate;
	}

	public void setTreatmentStartDate(java.util.Date treatmentStartDate) {
		this.treatmentStartDate = treatmentStartDate;
	}

	public Treatment(java.lang.String step, java.lang.String id,
			java.lang.String type, java.util.Date treatmentStartDate) {
		this.step = step;
		this.id = id;
		this.type = type;
		this.treatmentStartDate = treatmentStartDate;
	}

}